name: build .Net and Scala

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
        dotnet-quality: 'ga'

    - name: Restore .NET dependencies
      run: dotnet restore CSharp/aoc2022.csproj

    - name: Build .NET
      run: dotnet build CSharp/aoc2022.csproj --no-restore

    - name: Test .NET
      run: dotnet test CSharp/aoc2022.csproj --no-build --verbosity normal
